---
deployment:
  tasks:
    - export DEPLOYPATH=/home/sahabatg/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp landing.html $DEPLOYPATH
    - /bin/cp package-lock.json $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH
    - /bin/cp tailwind.config.js $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R node_modules $DEPLOYPATH
    - /bin/cp -R readme $DEPLOYPATH
    - /bin/cp -R webfonts $DEPLOYPATH
